# Generated by Django 2.2 on 2023-12-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(default=None)),
                ('create_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='resModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('create_at', models.DateTimeField(default=None)),
                ('position', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EMS_HR.positionModel')),
            ],
        ),
    ]
