# Generated by Django 2.2 on 2023-12-21 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EMS_HR', '0004_auto_20231221_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=10)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('create_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='projectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('deadline', models.DateField()),
                ('cost', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('create_at', models.DateTimeField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
