# Generated by Django 2.2 on 2023-12-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0005_projectmodel_updatemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projectModel',
        ),
    ]
