# Generated by Django 2.2 on 2023-12-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0006_delete_projectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('partner', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('deadline', models.DateField()),
                ('cost', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('create_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
