# Generated by Django 2.2 on 2023-12-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0007_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatemodel',
            name='proj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EMS_HR.projectModel'),
        ),
    ]
