# Generated by Django 2.2 on 2023-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0009_auto_20231222_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.CharField(default='on-going', max_length=12),
        ),
    ]
