# Generated by Django 2.2 on 2023-12-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0011_updatemodel_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empcreateModel',
        ),
    ]
