# Generated by Django 2.2 on 2023-12-24 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EMS_HR', '0012_delete_empcreatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='empcreateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=16)),
                ('salary', models.CharField(max_length=50)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('create_at', models.DateTimeField(default=None)),
                ('gender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EMS_HR.genderModel')),
                ('position', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EMS_HR.positionModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
