# Generated by Django 2.2 on 2023-12-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0013_empcreatemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empcreatemodel',
            old_name='user',
            new_name='employee',
        ),
    ]
