# Generated by Django 2.2 on 2023-12-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0014_auto_20231224_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empcreatemodel',
            old_name='employee',
            new_name='user',
        ),
    ]
