# Generated by Django 2.2 on 2023-12-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0015_auto_20231224_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empcreatemodel',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='EMS_HR.genderModel'),
        ),
    ]
