# Generated by Django 2.2 on 2023-12-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0016_auto_20231226_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empcreatemodel',
            name='gender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EMS_HR.genderModel'),
        ),
        migrations.AlterField(
            model_name='empcreatemodel',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
