# Generated by Django 2.2 on 2023-12-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0017_auto_20231226_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empcreatemodel',
            name='gender',
        ),
    ]
