# Generated by Django 2.2 on 2023-12-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_HR', '0018_remove_empcreatemodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='empcreatemodel',
            name='gender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EMS_HR.genderModel'),
        ),
    ]
