from django.urls import path
from EMS_HR.views import *

urlpatterns =[
    path('dashboard/', dashboard_view, name="dash"),
    path('emp/create/', emp_create, name="emp_create"),
    path('emp/view/', emp_view, name="emp_view"),
    path('search_by/', search_by),
    path('search_by1/', search_by1),
    path('search_by2/', search_by2),
    path('search_by3/', search_by3),
    path('emp/delete/<int:post_id>/', emp_delete),
    path('emp/detail/<int:post_id>/', emp_detail),
    path('emp/update/<int:post_id>/', emp_update),
    path('profile/upload/<int:user_id>/', profile_upload),
    path('profile/<int:user_id>/', profile),
    path('profile/create/', profile_create, name="prof_create"),
    path('mail/', mail, name="mail"),
    path('mail/delete/<int:post_id>/', mail_delete),
    path('leave/create/', leave_create,name="leave"),
    path('res/create/', res_create ,name="res"),
    path('leave/view/', leave_view, name="leave_view"),
    path('res/view/', res_view, name="res_view"),
    path('leave/approve/<int:id>/', leave_approve),
    path('leave/reject/<int:id>/', leave_reject),
    path('res/approve/<int:id>/', res_approve),
    path('res/reject/<int:id>/', res_reject),
    path('leave/detail/<int:post_id>/', leave_detail),
    path('leave/delete/<int:post_id>/', leave_delete),
    path('res/detail/<int:post_id>/', res_detail),
    path('res/delete/<int:post_id>/', res_delete),
    path('proj/create/', proj_create, name="proj_create"),
    path('proj/view/', proj_view, name="proj_view"),
    path('Proj/delete/<int:post_id>/', Proj_delete),
    path('proj/detail/<int:post_id>/', proj_detail),
    path('proj/dev/create/<int:post_id>/', proj_dev_create),
    path('proj/finish/<int:id>/', proj_finish),
    path('proj/edit/<int:post_id>/<int:proj_id>/', proj_edit),
    path('proj/delete/<int:post_id>/<int:proj_id>/', proj_delete),
]